name: Deploy demo holbox BE to EC2

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Setup SSH
      run: |
        mkdir -p ~/.ssh
        echo "${{ secrets.EC2_SSH_KEY }}" > ~/.ssh/id_rsa
        chmod 600 ~/.ssh/id_rsa
        ssh-keyscan -H ${{ secrets.EC2_HOST }} >> ~/.ssh/known_hosts

    - name: Deploy and run backend
      env:
        OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
      run: |
        ssh -o StrictHostKeyChecking=no ${{ secrets.EC2_USER }}@${{ secrets.EC2_HOST }} << 'EOF'
          set -e

          # Clone repo if not exists
          if [ ! -d "demo-backend" ]; then
            git clone git@github.com:HolboxAI/demo-backend.git
          fi

          cd demo-backend

          # Create/activate venv
          python3 -m venv venv
          source venv/bin/activate

          # Install requirements
          pip install -r requirements.txt

          # Write .env file
          echo "OPENAI_API_KEY=${OPENAI_API_KEY}" > .env

          # Kill existing uvicorn if running
          pkill -f "uvicorn" || true

          # Run app in background
          nohup bash -c 'source venv/bin/activate && export $(grep -v '^#' .env | xargs) && uvicorn app:app --host 0.0.0.0 --port 8000 --reload' > backend.log 2>&1 &
        EOF
